version: "3.8"

services:

  jenkins_server:
    container_name: jenkins_server
    image: jenkins_server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      HOST_IP: ${HOST_IP}
      HOST_PORT: ${HOST_PORT}
    ports:
      - ${HOST_PORT}:8080
      - 50000:50000
    env_file:
      - .env
    volumes:
      - jenkins_home:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home:
    name: jenkins_home
